version: "3"

includes:
  front:
    taskfile: Taskfile.front.yml
  back:
    taskfile: Taskfile.back.yml
  simulator:
    taskfile: Taskfile.simulator.yml

vars:
  MODULES_DIRS:
    sh: awk '/use \(/,/\)/ { if ($1 ~ /^\./) print $1 }' go.work

tasks:
  format:
    desc: Format all code (front, back, simulator)
    cmds:
      - task: front:format
      - task: back:format
      - task: simulator:format

  lint:
    desc: Lint all code (front, back, simulator)
    cmds:
      - task: front:lint
      - task: back:lint
      - task: simulator:lint

  build:
    desc: Build all modules (back, simulator)
    deps: [tidy]
    cmds:
      - task: back:build
      - task: simulator:build

  test:
    desc: Run all tests (simulator)
    deps: [build]
    cmds:
      - task: simulator:test

  tidy:
    desc: Execute tidy on all Go modules
    cmds:
      - task: back:tidy
      - task: simulator:tidy

  ci:
    desc: Launch all tasks for CI
    deps: [build, lint, test]

  dev:
    desc: Start all services (front + back)
    cmds:
      - echo "Starting all services..."
      - task: back:dev
      - task: front:dev

  dev:front:
    desc: Start front-end only
    cmds:
      - task: front:start

  dev:back:
    desc: Start back-end only
    cmds:
      - task: back:start

  start:prod:aio:
    desc: Start production environment with Docker Compose
    cmds:
      - docker compose -f docker-compose.yml up --pull always

  start:prod:
    desc: Start production islands environment
    cmds:
      - docker compose -f docker-compose.islands.yml up --pull always

  start:local:aio:
    desc: Start local islands environment
    cmds:
      - docker compose -f docker-compose.local.yml up --build

  start:local:
    desc: Start local islands environment
    cmds:
      - docker compose -f docker-compose.local.islands.yml up --build

  clean:
    desc: Clean back-end containers
    cmds:
      - task: back:clean

  generate-sdk:
    desc: Generate SDK and API types
    cmds:
      - task: back:generate-sdk

  prod-docker-build:
    desc: Test docker image creations for backend, simulator, runner and all-in-one
    deps: [tidy]
    cmds:
      - defer: docker image rm devsforge-local-backend-test:latest > /dev/null || true
      - defer: docker image rm devsforge-local-simulator-test:latest > /dev/null || true
      - defer: docker image rm devsforge-local-runner-test:latest > /dev/null || true
      - defer: docker image rm devsforge-local-aio-test:latest > /dev/null || true
      - docker build -f ./back/Dockerfile --target backend -t devsforge-local-backend-test:latest ./
      - docker build -f ./back/Dockerfile --target simulator -t devsforge-local-simulator-test:latest ./
      - docker build -f ./back/Dockerfile --target runner -t devsforge-local-runner-test:latest ./
      - docker build -f ./back/Dockerfile -t devsforge-local-aio-test:latest ./