# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import devs_pb2 as proto_dot_devs__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/devs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DevsModelStub(object):
    """Service générique pour piloter un modèle DEVS
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/devs.DevsModel/Initialize',
                request_serializer=proto_dot_devs__pb2.InitializeRequest.SerializeToString,
                response_deserializer=proto_dot_devs__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.TimeAdvance = channel.unary_unary(
                '/devs.DevsModel/TimeAdvance',
                request_serializer=proto_dot_devs__pb2.TimeAdvanceRequest.SerializeToString,
                response_deserializer=proto_dot_devs__pb2.TimeAdvanceResponse.FromString,
                _registered_method=True)
        self.InternalTransition = channel.unary_unary(
                '/devs.DevsModel/InternalTransition',
                request_serializer=proto_dot_devs__pb2.InternalTransitionRequest.SerializeToString,
                response_deserializer=proto_dot_devs__pb2.InternalTransitionResponse.FromString,
                _registered_method=True)
        self.ExternalTransition = channel.unary_unary(
                '/devs.DevsModel/ExternalTransition',
                request_serializer=proto_dot_devs__pb2.ExternalTransitionRequest.SerializeToString,
                response_deserializer=proto_dot_devs__pb2.ExternalTransitionResponse.FromString,
                _registered_method=True)
        self.ConfluentTransition = channel.unary_unary(
                '/devs.DevsModel/ConfluentTransition',
                request_serializer=proto_dot_devs__pb2.ConfluentTransitionRequest.SerializeToString,
                response_deserializer=proto_dot_devs__pb2.ConfluentTransitionResponse.FromString,
                _registered_method=True)
        self.Output = channel.unary_unary(
                '/devs.DevsModel/Output',
                request_serializer=proto_dot_devs__pb2.OutputRequest.SerializeToString,
                response_deserializer=proto_dot_devs__pb2.OutputResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/devs.DevsModel/GetState',
                request_serializer=proto_dot_devs__pb2.GetStateRequest.SerializeToString,
                response_deserializer=proto_dot_devs__pb2.GetStateResponse.FromString,
                _registered_method=True)


class DevsModelServicer(object):
    """Service générique pour piloter un modèle DEVS
    """

    def Initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TimeAdvance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InternalTransition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExternalTransition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfluentTransition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Output(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DevsModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=proto_dot_devs__pb2.InitializeRequest.FromString,
                    response_serializer=proto_dot_devs__pb2.InitializeResponse.SerializeToString,
            ),
            'TimeAdvance': grpc.unary_unary_rpc_method_handler(
                    servicer.TimeAdvance,
                    request_deserializer=proto_dot_devs__pb2.TimeAdvanceRequest.FromString,
                    response_serializer=proto_dot_devs__pb2.TimeAdvanceResponse.SerializeToString,
            ),
            'InternalTransition': grpc.unary_unary_rpc_method_handler(
                    servicer.InternalTransition,
                    request_deserializer=proto_dot_devs__pb2.InternalTransitionRequest.FromString,
                    response_serializer=proto_dot_devs__pb2.InternalTransitionResponse.SerializeToString,
            ),
            'ExternalTransition': grpc.unary_unary_rpc_method_handler(
                    servicer.ExternalTransition,
                    request_deserializer=proto_dot_devs__pb2.ExternalTransitionRequest.FromString,
                    response_serializer=proto_dot_devs__pb2.ExternalTransitionResponse.SerializeToString,
            ),
            'ConfluentTransition': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfluentTransition,
                    request_deserializer=proto_dot_devs__pb2.ConfluentTransitionRequest.FromString,
                    response_serializer=proto_dot_devs__pb2.ConfluentTransitionResponse.SerializeToString,
            ),
            'Output': grpc.unary_unary_rpc_method_handler(
                    servicer.Output,
                    request_deserializer=proto_dot_devs__pb2.OutputRequest.FromString,
                    response_serializer=proto_dot_devs__pb2.OutputResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=proto_dot_devs__pb2.GetStateRequest.FromString,
                    response_serializer=proto_dot_devs__pb2.GetStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'devs.DevsModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('devs.DevsModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DevsModel(object):
    """Service générique pour piloter un modèle DEVS
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devs.DevsModel/Initialize',
            proto_dot_devs__pb2.InitializeRequest.SerializeToString,
            proto_dot_devs__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TimeAdvance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devs.DevsModel/TimeAdvance',
            proto_dot_devs__pb2.TimeAdvanceRequest.SerializeToString,
            proto_dot_devs__pb2.TimeAdvanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InternalTransition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devs.DevsModel/InternalTransition',
            proto_dot_devs__pb2.InternalTransitionRequest.SerializeToString,
            proto_dot_devs__pb2.InternalTransitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExternalTransition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devs.DevsModel/ExternalTransition',
            proto_dot_devs__pb2.ExternalTransitionRequest.SerializeToString,
            proto_dot_devs__pb2.ExternalTransitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfluentTransition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devs.DevsModel/ConfluentTransition',
            proto_dot_devs__pb2.ConfluentTransitionRequest.SerializeToString,
            proto_dot_devs__pb2.ConfluentTransitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Output(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devs.DevsModel/Output',
            proto_dot_devs__pb2.OutputRequest.SerializeToString,
            proto_dot_devs__pb2.OutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devs.DevsModel/GetState',
            proto_dot_devs__pb2.GetStateRequest.SerializeToString,
            proto_dot_devs__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
