# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/devs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/devs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/devs.proto\x12\x04\x64\x65vs\x1a\x19google/protobuf/any.proto\"<\n\x11InitializeRequest\x12\'\n\targuments\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\"\x14\n\x12InitializeResponse\"\x14\n\x12TimeAdvanceRequest\"$\n\x13TimeAdvanceResponse\x12\r\n\x05sigma\x18\x01 \x01(\x01\"/\n\tPortEvent\x12\x11\n\tport_name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x1b\n\x19InternalTransitionRequest\"\x1c\n\x1aInternalTransitionResponse\"M\n\x19\x45xternalTransitionRequest\x12\x0f\n\x07\x65lapsed\x18\x01 \x01(\x01\x12\x1f\n\x06inputs\x18\x02 \x03(\x0b\x32\x0f.devs.PortEvent\"\x1c\n\x1a\x45xternalTransitionResponse\"N\n\x1a\x43onfluentTransitionRequest\x12\x0f\n\x07\x65lapsed\x18\x01 \x01(\x01\x12\x1f\n\x06inputs\x18\x02 \x03(\x0b\x32\x0f.devs.PortEvent\"\x1d\n\x1b\x43onfluentTransitionResponse\"\x0f\n\rOutputRequest\"2\n\x0eOutputResponse\x12 \n\x07outputs\x18\x01 \x03(\x0b\x32\x0f.devs.PortEvent\"\x11\n\x0fGetStateRequest\"F\n\x10GetStateResponse\x12\r\n\x05phase\x18\x01 \x01(\t\x12\r\n\x05sigma\x18\x02 \x01(\x01\x12\x14\n\x0cstate_string\x18\x03 \x01(\t2\x8e\x04\n\tDevsModel\x12?\n\nInitialize\x12\x17.devs.InitializeRequest\x1a\x18.devs.InitializeResponse\x12\x42\n\x0bTimeAdvance\x12\x18.devs.TimeAdvanceRequest\x1a\x19.devs.TimeAdvanceResponse\x12W\n\x12InternalTransition\x12\x1f.devs.InternalTransitionRequest\x1a .devs.InternalTransitionResponse\x12W\n\x12\x45xternalTransition\x12\x1f.devs.ExternalTransitionRequest\x1a .devs.ExternalTransitionResponse\x12Z\n\x13\x43onfluentTransition\x12 .devs.ConfluentTransitionRequest\x1a!.devs.ConfluentTransitionResponse\x12\x33\n\x06Output\x12\x13.devs.OutputRequest\x1a\x14.devs.OutputResponse\x12\x39\n\x08GetState\x12\x15.devs.GetStateRequest\x1a\x16.devs.GetStateResponseB Z\x1e\x64\x65vsforge/runners/proto;devspbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.devs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036devsforge/runners/proto;devspb'
  _globals['_INITIALIZEREQUEST']._serialized_start=53
  _globals['_INITIALIZEREQUEST']._serialized_end=113
  _globals['_INITIALIZERESPONSE']._serialized_start=115
  _globals['_INITIALIZERESPONSE']._serialized_end=135
  _globals['_TIMEADVANCEREQUEST']._serialized_start=137
  _globals['_TIMEADVANCEREQUEST']._serialized_end=157
  _globals['_TIMEADVANCERESPONSE']._serialized_start=159
  _globals['_TIMEADVANCERESPONSE']._serialized_end=195
  _globals['_PORTEVENT']._serialized_start=197
  _globals['_PORTEVENT']._serialized_end=244
  _globals['_INTERNALTRANSITIONREQUEST']._serialized_start=246
  _globals['_INTERNALTRANSITIONREQUEST']._serialized_end=273
  _globals['_INTERNALTRANSITIONRESPONSE']._serialized_start=275
  _globals['_INTERNALTRANSITIONRESPONSE']._serialized_end=303
  _globals['_EXTERNALTRANSITIONREQUEST']._serialized_start=305
  _globals['_EXTERNALTRANSITIONREQUEST']._serialized_end=382
  _globals['_EXTERNALTRANSITIONRESPONSE']._serialized_start=384
  _globals['_EXTERNALTRANSITIONRESPONSE']._serialized_end=412
  _globals['_CONFLUENTTRANSITIONREQUEST']._serialized_start=414
  _globals['_CONFLUENTTRANSITIONREQUEST']._serialized_end=492
  _globals['_CONFLUENTTRANSITIONRESPONSE']._serialized_start=494
  _globals['_CONFLUENTTRANSITIONRESPONSE']._serialized_end=523
  _globals['_OUTPUTREQUEST']._serialized_start=525
  _globals['_OUTPUTREQUEST']._serialized_end=540
  _globals['_OUTPUTRESPONSE']._serialized_start=542
  _globals['_OUTPUTRESPONSE']._serialized_end=592
  _globals['_GETSTATEREQUEST']._serialized_start=594
  _globals['_GETSTATEREQUEST']._serialized_end=611
  _globals['_GETSTATERESPONSE']._serialized_start=613
  _globals['_GETSTATERESPONSE']._serialized_end=683
  _globals['_DEVSMODEL']._serialized_start=686
  _globals['_DEVSMODEL']._serialized_end=1212
# @@protoc_insertion_point(module_scope)
