FROM golang:1.25.4

WORKDIR /app

COPY go.work ./
COPY simulator/coordinator/go.mod simulator/coordinator/go.sum* ./simulator/coordinator/
COPY simulator/runner/go.mod simulator/runner/go.sum* ./simulator/runner/
COPY simulator/shared/go.mod simulator/shared/go.sum* ./simulator/shared/

COPY simulator ./simulator

CMD ["sh", "-c", "CGO_ENABLED=0 go build -ldflags='-s -w' -o /build/devsforge-runner ./simulator/runner"]
