// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: devs.proto

package devspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AtomicModelService_Initialize_FullMethodName          = "/devsforge.devs.AtomicModelService/Initialize"
	AtomicModelService_Finalize_FullMethodName            = "/devsforge.devs.AtomicModelService/Finalize"
	AtomicModelService_TimeAdvance_FullMethodName         = "/devsforge.devs.AtomicModelService/TimeAdvance"
	AtomicModelService_InternalTransition_FullMethodName  = "/devsforge.devs.AtomicModelService/InternalTransition"
	AtomicModelService_ExternalTransition_FullMethodName  = "/devsforge.devs.AtomicModelService/ExternalTransition"
	AtomicModelService_ConfluentTransition_FullMethodName = "/devsforge.devs.AtomicModelService/ConfluentTransition"
	AtomicModelService_Output_FullMethodName              = "/devsforge.devs.AtomicModelService/Output"
	AtomicModelService_AddInput_FullMethodName            = "/devsforge.devs.AtomicModelService/AddInput"
)

// AtomicModelServiceClient is the client API for AtomicModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AtomicModelServiceClient interface {
	// Initialisation du modèle (Component.Initialize)
	Initialize(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Fin de simulation / nettoyage (Component.Exit)
	Finalize(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// TimeAdvance() : renvoie sigma (TA)
	TimeAdvance(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TimeAdvanceResponse, error)
	// InternalTransition() : DeltInt
	InternalTransition(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ExternalTransition(e) : DeltExt
	ExternalTransition(ctx context.Context, in *ElapsedTime, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ConfluentTransition(e) : DeltCon
	ConfluentTransition(ctx context.Context, in *ElapsedTime, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Output() : Lambda
	// Le wrapper lit les ports de sortie du modèle, construit OutputResponse,
	// et peut ensuite vider les ports si c'est ta convention.
	Output(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OutputResponse, error)
	// Injection d'une valeur dans un port d'entrée (AddValue sur un inPort)
	// C'est ce que le runner va appeler quand il reçoit un message pour ce modèle.
	AddInput(ctx context.Context, in *InputMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type atomicModelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAtomicModelServiceClient(cc grpc.ClientConnInterface) AtomicModelServiceClient {
	return &atomicModelServiceClient{cc}
}

func (c *atomicModelServiceClient) Initialize(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AtomicModelService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atomicModelServiceClient) Finalize(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AtomicModelService_Finalize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atomicModelServiceClient) TimeAdvance(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TimeAdvanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeAdvanceResponse)
	err := c.cc.Invoke(ctx, AtomicModelService_TimeAdvance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atomicModelServiceClient) InternalTransition(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AtomicModelService_InternalTransition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atomicModelServiceClient) ExternalTransition(ctx context.Context, in *ElapsedTime, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AtomicModelService_ExternalTransition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atomicModelServiceClient) ConfluentTransition(ctx context.Context, in *ElapsedTime, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AtomicModelService_ConfluentTransition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atomicModelServiceClient) Output(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OutputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutputResponse)
	err := c.cc.Invoke(ctx, AtomicModelService_Output_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atomicModelServiceClient) AddInput(ctx context.Context, in *InputMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AtomicModelService_AddInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AtomicModelServiceServer is the server API for AtomicModelService service.
// All implementations must embed UnimplementedAtomicModelServiceServer
// for forward compatibility.
type AtomicModelServiceServer interface {
	// Initialisation du modèle (Component.Initialize)
	Initialize(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Fin de simulation / nettoyage (Component.Exit)
	Finalize(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// TimeAdvance() : renvoie sigma (TA)
	TimeAdvance(context.Context, *emptypb.Empty) (*TimeAdvanceResponse, error)
	// InternalTransition() : DeltInt
	InternalTransition(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// ExternalTransition(e) : DeltExt
	ExternalTransition(context.Context, *ElapsedTime) (*emptypb.Empty, error)
	// ConfluentTransition(e) : DeltCon
	ConfluentTransition(context.Context, *ElapsedTime) (*emptypb.Empty, error)
	// Output() : Lambda
	// Le wrapper lit les ports de sortie du modèle, construit OutputResponse,
	// et peut ensuite vider les ports si c'est ta convention.
	Output(context.Context, *emptypb.Empty) (*OutputResponse, error)
	// Injection d'une valeur dans un port d'entrée (AddValue sur un inPort)
	// C'est ce que le runner va appeler quand il reçoit un message pour ce modèle.
	AddInput(context.Context, *InputMessage) (*emptypb.Empty, error)
	mustEmbedUnimplementedAtomicModelServiceServer()
}

// UnimplementedAtomicModelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAtomicModelServiceServer struct{}

func (UnimplementedAtomicModelServiceServer) Initialize(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedAtomicModelServiceServer) Finalize(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Finalize not implemented")
}
func (UnimplementedAtomicModelServiceServer) TimeAdvance(context.Context, *emptypb.Empty) (*TimeAdvanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimeAdvance not implemented")
}
func (UnimplementedAtomicModelServiceServer) InternalTransition(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalTransition not implemented")
}
func (UnimplementedAtomicModelServiceServer) ExternalTransition(context.Context, *ElapsedTime) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExternalTransition not implemented")
}
func (UnimplementedAtomicModelServiceServer) ConfluentTransition(context.Context, *ElapsedTime) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfluentTransition not implemented")
}
func (UnimplementedAtomicModelServiceServer) Output(context.Context, *emptypb.Empty) (*OutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Output not implemented")
}
func (UnimplementedAtomicModelServiceServer) AddInput(context.Context, *InputMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddInput not implemented")
}
func (UnimplementedAtomicModelServiceServer) mustEmbedUnimplementedAtomicModelServiceServer() {}
func (UnimplementedAtomicModelServiceServer) testEmbeddedByValue()                            {}

// UnsafeAtomicModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AtomicModelServiceServer will
// result in compilation errors.
type UnsafeAtomicModelServiceServer interface {
	mustEmbedUnimplementedAtomicModelServiceServer()
}

func RegisterAtomicModelServiceServer(s grpc.ServiceRegistrar, srv AtomicModelServiceServer) {
	// If the following call pancis, it indicates UnimplementedAtomicModelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AtomicModelService_ServiceDesc, srv)
}

func _AtomicModelService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtomicModelServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtomicModelService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtomicModelServiceServer).Initialize(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtomicModelService_Finalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtomicModelServiceServer).Finalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtomicModelService_Finalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtomicModelServiceServer).Finalize(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtomicModelService_TimeAdvance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtomicModelServiceServer).TimeAdvance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtomicModelService_TimeAdvance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtomicModelServiceServer).TimeAdvance(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtomicModelService_InternalTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtomicModelServiceServer).InternalTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtomicModelService_InternalTransition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtomicModelServiceServer).InternalTransition(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtomicModelService_ExternalTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElapsedTime)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtomicModelServiceServer).ExternalTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtomicModelService_ExternalTransition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtomicModelServiceServer).ExternalTransition(ctx, req.(*ElapsedTime))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtomicModelService_ConfluentTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElapsedTime)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtomicModelServiceServer).ConfluentTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtomicModelService_ConfluentTransition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtomicModelServiceServer).ConfluentTransition(ctx, req.(*ElapsedTime))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtomicModelService_Output_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtomicModelServiceServer).Output(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtomicModelService_Output_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtomicModelServiceServer).Output(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtomicModelService_AddInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtomicModelServiceServer).AddInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtomicModelService_AddInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtomicModelServiceServer).AddInput(ctx, req.(*InputMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// AtomicModelService_ServiceDesc is the grpc.ServiceDesc for AtomicModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AtomicModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devsforge.devs.AtomicModelService",
	HandlerType: (*AtomicModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _AtomicModelService_Initialize_Handler,
		},
		{
			MethodName: "Finalize",
			Handler:    _AtomicModelService_Finalize_Handler,
		},
		{
			MethodName: "TimeAdvance",
			Handler:    _AtomicModelService_TimeAdvance_Handler,
		},
		{
			MethodName: "InternalTransition",
			Handler:    _AtomicModelService_InternalTransition_Handler,
		},
		{
			MethodName: "ExternalTransition",
			Handler:    _AtomicModelService_ExternalTransition_Handler,
		},
		{
			MethodName: "ConfluentTransition",
			Handler:    _AtomicModelService_ConfluentTransition_Handler,
		},
		{
			MethodName: "Output",
			Handler:    _AtomicModelService_Output_Handler,
		},
		{
			MethodName: "AddInput",
			Handler:    _AtomicModelService_AddInput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "devs.proto",
}
