// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: runners/proto/devs.proto

package devspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DevsModel_Initialize_FullMethodName          = "/devs.DevsModel/Initialize"
	DevsModel_TimeAdvance_FullMethodName         = "/devs.DevsModel/TimeAdvance"
	DevsModel_InternalTransition_FullMethodName  = "/devs.DevsModel/InternalTransition"
	DevsModel_ExternalTransition_FullMethodName  = "/devs.DevsModel/ExternalTransition"
	DevsModel_ConfluentTransition_FullMethodName = "/devs.DevsModel/ConfluentTransition"
	DevsModel_Output_FullMethodName              = "/devs.DevsModel/Output"
	DevsModel_GetState_FullMethodName            = "/devs.DevsModel/GetState"
)

// DevsModelClient is the client API for DevsModel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service générique pour piloter un modèle DEVS
type DevsModelClient interface {
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	TimeAdvance(ctx context.Context, in *TimeAdvanceRequest, opts ...grpc.CallOption) (*TimeAdvanceResponse, error)
	InternalTransition(ctx context.Context, in *InternalTransitionRequest, opts ...grpc.CallOption) (*InternalTransitionResponse, error)
	ExternalTransition(ctx context.Context, in *ExternalTransitionRequest, opts ...grpc.CallOption) (*ExternalTransitionResponse, error)
	ConfluentTransition(ctx context.Context, in *ConfluentTransitionRequest, opts ...grpc.CallOption) (*ConfluentTransitionResponse, error)
	Output(ctx context.Context, in *OutputRequest, opts ...grpc.CallOption) (*OutputResponse, error)
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
}

type devsModelClient struct {
	cc grpc.ClientConnInterface
}

func NewDevsModelClient(cc grpc.ClientConnInterface) DevsModelClient {
	return &devsModelClient{cc}
}

func (c *devsModelClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, DevsModel_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devsModelClient) TimeAdvance(ctx context.Context, in *TimeAdvanceRequest, opts ...grpc.CallOption) (*TimeAdvanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeAdvanceResponse)
	err := c.cc.Invoke(ctx, DevsModel_TimeAdvance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devsModelClient) InternalTransition(ctx context.Context, in *InternalTransitionRequest, opts ...grpc.CallOption) (*InternalTransitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalTransitionResponse)
	err := c.cc.Invoke(ctx, DevsModel_InternalTransition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devsModelClient) ExternalTransition(ctx context.Context, in *ExternalTransitionRequest, opts ...grpc.CallOption) (*ExternalTransitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalTransitionResponse)
	err := c.cc.Invoke(ctx, DevsModel_ExternalTransition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devsModelClient) ConfluentTransition(ctx context.Context, in *ConfluentTransitionRequest, opts ...grpc.CallOption) (*ConfluentTransitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfluentTransitionResponse)
	err := c.cc.Invoke(ctx, DevsModel_ConfluentTransition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devsModelClient) Output(ctx context.Context, in *OutputRequest, opts ...grpc.CallOption) (*OutputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutputResponse)
	err := c.cc.Invoke(ctx, DevsModel_Output_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devsModelClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, DevsModel_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevsModelServer is the server API for DevsModel service.
// All implementations must embed UnimplementedDevsModelServer
// for forward compatibility.
//
// Service générique pour piloter un modèle DEVS
type DevsModelServer interface {
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	TimeAdvance(context.Context, *TimeAdvanceRequest) (*TimeAdvanceResponse, error)
	InternalTransition(context.Context, *InternalTransitionRequest) (*InternalTransitionResponse, error)
	ExternalTransition(context.Context, *ExternalTransitionRequest) (*ExternalTransitionResponse, error)
	ConfluentTransition(context.Context, *ConfluentTransitionRequest) (*ConfluentTransitionResponse, error)
	Output(context.Context, *OutputRequest) (*OutputResponse, error)
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	mustEmbedUnimplementedDevsModelServer()
}

// UnimplementedDevsModelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDevsModelServer struct{}

func (UnimplementedDevsModelServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedDevsModelServer) TimeAdvance(context.Context, *TimeAdvanceRequest) (*TimeAdvanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimeAdvance not implemented")
}
func (UnimplementedDevsModelServer) InternalTransition(context.Context, *InternalTransitionRequest) (*InternalTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalTransition not implemented")
}
func (UnimplementedDevsModelServer) ExternalTransition(context.Context, *ExternalTransitionRequest) (*ExternalTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExternalTransition not implemented")
}
func (UnimplementedDevsModelServer) ConfluentTransition(context.Context, *ConfluentTransitionRequest) (*ConfluentTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfluentTransition not implemented")
}
func (UnimplementedDevsModelServer) Output(context.Context, *OutputRequest) (*OutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Output not implemented")
}
func (UnimplementedDevsModelServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedDevsModelServer) mustEmbedUnimplementedDevsModelServer() {}
func (UnimplementedDevsModelServer) testEmbeddedByValue()                   {}

// UnsafeDevsModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevsModelServer will
// result in compilation errors.
type UnsafeDevsModelServer interface {
	mustEmbedUnimplementedDevsModelServer()
}

func RegisterDevsModelServer(s grpc.ServiceRegistrar, srv DevsModelServer) {
	// If the following call pancis, it indicates UnimplementedDevsModelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DevsModel_ServiceDesc, srv)
}

func _DevsModel_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevsModelServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevsModel_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevsModelServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevsModel_TimeAdvance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeAdvanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevsModelServer).TimeAdvance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevsModel_TimeAdvance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevsModelServer).TimeAdvance(ctx, req.(*TimeAdvanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevsModel_InternalTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevsModelServer).InternalTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevsModel_InternalTransition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevsModelServer).InternalTransition(ctx, req.(*InternalTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevsModel_ExternalTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevsModelServer).ExternalTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevsModel_ExternalTransition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevsModelServer).ExternalTransition(ctx, req.(*ExternalTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevsModel_ConfluentTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfluentTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevsModelServer).ConfluentTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevsModel_ConfluentTransition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevsModelServer).ConfluentTransition(ctx, req.(*ConfluentTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevsModel_Output_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevsModelServer).Output(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevsModel_Output_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevsModelServer).Output(ctx, req.(*OutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevsModel_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevsModelServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevsModel_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevsModelServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DevsModel_ServiceDesc is the grpc.ServiceDesc for DevsModel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DevsModel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devs.DevsModel",
	HandlerType: (*DevsModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _DevsModel_Initialize_Handler,
		},
		{
			MethodName: "TimeAdvance",
			Handler:    _DevsModel_TimeAdvance_Handler,
		},
		{
			MethodName: "InternalTransition",
			Handler:    _DevsModel_InternalTransition_Handler,
		},
		{
			MethodName: "ExternalTransition",
			Handler:    _DevsModel_ExternalTransition_Handler,
		},
		{
			MethodName: "ConfluentTransition",
			Handler:    _DevsModel_ConfluentTransition_Handler,
		},
		{
			MethodName: "Output",
			Handler:    _DevsModel_Output_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _DevsModel_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runners/proto/devs.proto",
}
