// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: runners/proto/devs.proto

package devspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_runners_proto_devs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_runners_proto_devs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{1}
}

type TimeAdvanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeAdvanceRequest) Reset() {
	*x = TimeAdvanceRequest{}
	mi := &file_runners_proto_devs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeAdvanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeAdvanceRequest) ProtoMessage() {}

func (x *TimeAdvanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeAdvanceRequest.ProtoReflect.Descriptor instead.
func (*TimeAdvanceRequest) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{2}
}

type TimeAdvanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sigma         float64                `protobuf:"fixed64,1,opt,name=sigma,proto3" json:"sigma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeAdvanceResponse) Reset() {
	*x = TimeAdvanceResponse{}
	mi := &file_runners_proto_devs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeAdvanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeAdvanceResponse) ProtoMessage() {}

func (x *TimeAdvanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeAdvanceResponse.ProtoReflect.Descriptor instead.
func (*TimeAdvanceResponse) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{3}
}

func (x *TimeAdvanceResponse) GetSigma() float64 {
	if x != nil {
		return x.Sigma
	}
	return 0
}

type PortEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortName      string                 `protobuf:"bytes,1,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // tu pourras le changer en string/json plus tard
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortEvent) Reset() {
	*x = PortEvent{}
	mi := &file_runners_proto_devs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortEvent) ProtoMessage() {}

func (x *PortEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortEvent.ProtoReflect.Descriptor instead.
func (*PortEvent) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{4}
}

func (x *PortEvent) GetPortName() string {
	if x != nil {
		return x.PortName
	}
	return ""
}

func (x *PortEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InternalTransitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalTransitionRequest) Reset() {
	*x = InternalTransitionRequest{}
	mi := &file_runners_proto_devs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalTransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalTransitionRequest) ProtoMessage() {}

func (x *InternalTransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalTransitionRequest.ProtoReflect.Descriptor instead.
func (*InternalTransitionRequest) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{5}
}

type InternalTransitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalTransitionResponse) Reset() {
	*x = InternalTransitionResponse{}
	mi := &file_runners_proto_devs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalTransitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalTransitionResponse) ProtoMessage() {}

func (x *InternalTransitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalTransitionResponse.ProtoReflect.Descriptor instead.
func (*InternalTransitionResponse) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{6}
}

type ExternalTransitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elapsed       float64                `protobuf:"fixed64,1,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Inputs        []*PortEvent           `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalTransitionRequest) Reset() {
	*x = ExternalTransitionRequest{}
	mi := &file_runners_proto_devs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalTransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalTransitionRequest) ProtoMessage() {}

func (x *ExternalTransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalTransitionRequest.ProtoReflect.Descriptor instead.
func (*ExternalTransitionRequest) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{7}
}

func (x *ExternalTransitionRequest) GetElapsed() float64 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

func (x *ExternalTransitionRequest) GetInputs() []*PortEvent {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type ExternalTransitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalTransitionResponse) Reset() {
	*x = ExternalTransitionResponse{}
	mi := &file_runners_proto_devs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalTransitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalTransitionResponse) ProtoMessage() {}

func (x *ExternalTransitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalTransitionResponse.ProtoReflect.Descriptor instead.
func (*ExternalTransitionResponse) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{8}
}

type ConfluentTransitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elapsed       float64                `protobuf:"fixed64,1,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Inputs        []*PortEvent           `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfluentTransitionRequest) Reset() {
	*x = ConfluentTransitionRequest{}
	mi := &file_runners_proto_devs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfluentTransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfluentTransitionRequest) ProtoMessage() {}

func (x *ConfluentTransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfluentTransitionRequest.ProtoReflect.Descriptor instead.
func (*ConfluentTransitionRequest) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{9}
}

func (x *ConfluentTransitionRequest) GetElapsed() float64 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

func (x *ConfluentTransitionRequest) GetInputs() []*PortEvent {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type ConfluentTransitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfluentTransitionResponse) Reset() {
	*x = ConfluentTransitionResponse{}
	mi := &file_runners_proto_devs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfluentTransitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfluentTransitionResponse) ProtoMessage() {}

func (x *ConfluentTransitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfluentTransitionResponse.ProtoReflect.Descriptor instead.
func (*ConfluentTransitionResponse) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{10}
}

type OutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputRequest) Reset() {
	*x = OutputRequest{}
	mi := &file_runners_proto_devs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputRequest) ProtoMessage() {}

func (x *OutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputRequest.ProtoReflect.Descriptor instead.
func (*OutputRequest) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{11}
}

type OutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*PortEvent           `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputResponse) Reset() {
	*x = OutputResponse{}
	mi := &file_runners_proto_devs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputResponse) ProtoMessage() {}

func (x *OutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputResponse.ProtoReflect.Descriptor instead.
func (*OutputResponse) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{12}
}

func (x *OutputResponse) GetOutputs() []*PortEvent {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_runners_proto_devs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{13}
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Sigma         float64                `protobuf:"fixed64,2,opt,name=sigma,proto3" json:"sigma,omitempty"`
	StateString   string                 `protobuf:"bytes,3,opt,name=state_string,json=stateString,proto3" json:"state_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_runners_proto_devs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runners_proto_devs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_runners_proto_devs_proto_rawDescGZIP(), []int{14}
}

func (x *GetStateResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *GetStateResponse) GetSigma() float64 {
	if x != nil {
		return x.Sigma
	}
	return 0
}

func (x *GetStateResponse) GetStateString() string {
	if x != nil {
		return x.StateString
	}
	return ""
}

var File_runners_proto_devs_proto protoreflect.FileDescriptor

const file_runners_proto_devs_proto_rawDesc = "" +
	"\n" +
	"\x18runners/proto/devs.proto\x12\x04devs\"2\n" +
	"\x11InitializeRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\"\x14\n" +
	"\x12InitializeResponse\"\x14\n" +
	"\x12TimeAdvanceRequest\"+\n" +
	"\x13TimeAdvanceResponse\x12\x14\n" +
	"\x05sigma\x18\x01 \x01(\x01R\x05sigma\"B\n" +
	"\tPortEvent\x12\x1b\n" +
	"\tport_name\x18\x01 \x01(\tR\bportName\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x1b\n" +
	"\x19InternalTransitionRequest\"\x1c\n" +
	"\x1aInternalTransitionResponse\"^\n" +
	"\x19ExternalTransitionRequest\x12\x18\n" +
	"\aelapsed\x18\x01 \x01(\x01R\aelapsed\x12'\n" +
	"\x06inputs\x18\x02 \x03(\v2\x0f.devs.PortEventR\x06inputs\"\x1c\n" +
	"\x1aExternalTransitionResponse\"_\n" +
	"\x1aConfluentTransitionRequest\x12\x18\n" +
	"\aelapsed\x18\x01 \x01(\x01R\aelapsed\x12'\n" +
	"\x06inputs\x18\x02 \x03(\v2\x0f.devs.PortEventR\x06inputs\"\x1d\n" +
	"\x1bConfluentTransitionResponse\"\x0f\n" +
	"\rOutputRequest\";\n" +
	"\x0eOutputResponse\x12)\n" +
	"\aoutputs\x18\x01 \x03(\v2\x0f.devs.PortEventR\aoutputs\"\x11\n" +
	"\x0fGetStateRequest\"a\n" +
	"\x10GetStateResponse\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x14\n" +
	"\x05sigma\x18\x02 \x01(\x01R\x05sigma\x12!\n" +
	"\fstate_string\x18\x03 \x01(\tR\vstateString2\x8e\x04\n" +
	"\tDevsModel\x12?\n" +
	"\n" +
	"Initialize\x12\x17.devs.InitializeRequest\x1a\x18.devs.InitializeResponse\x12B\n" +
	"\vTimeAdvance\x12\x18.devs.TimeAdvanceRequest\x1a\x19.devs.TimeAdvanceResponse\x12W\n" +
	"\x12InternalTransition\x12\x1f.devs.InternalTransitionRequest\x1a .devs.InternalTransitionResponse\x12W\n" +
	"\x12ExternalTransition\x12\x1f.devs.ExternalTransitionRequest\x1a .devs.ExternalTransitionResponse\x12Z\n" +
	"\x13ConfluentTransition\x12 .devs.ConfluentTransitionRequest\x1a!.devs.ConfluentTransitionResponse\x123\n" +
	"\x06Output\x12\x13.devs.OutputRequest\x1a\x14.devs.OutputResponse\x129\n" +
	"\bGetState\x12\x15.devs.GetStateRequest\x1a\x16.devs.GetStateResponseB Z\x1edevsforge/runners/proto;devspbb\x06proto3"

var (
	file_runners_proto_devs_proto_rawDescOnce sync.Once
	file_runners_proto_devs_proto_rawDescData []byte
)

func file_runners_proto_devs_proto_rawDescGZIP() []byte {
	file_runners_proto_devs_proto_rawDescOnce.Do(func() {
		file_runners_proto_devs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runners_proto_devs_proto_rawDesc), len(file_runners_proto_devs_proto_rawDesc)))
	})
	return file_runners_proto_devs_proto_rawDescData
}

var file_runners_proto_devs_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_runners_proto_devs_proto_goTypes = []any{
	(*InitializeRequest)(nil),           // 0: devs.InitializeRequest
	(*InitializeResponse)(nil),          // 1: devs.InitializeResponse
	(*TimeAdvanceRequest)(nil),          // 2: devs.TimeAdvanceRequest
	(*TimeAdvanceResponse)(nil),         // 3: devs.TimeAdvanceResponse
	(*PortEvent)(nil),                   // 4: devs.PortEvent
	(*InternalTransitionRequest)(nil),   // 5: devs.InternalTransitionRequest
	(*InternalTransitionResponse)(nil),  // 6: devs.InternalTransitionResponse
	(*ExternalTransitionRequest)(nil),   // 7: devs.ExternalTransitionRequest
	(*ExternalTransitionResponse)(nil),  // 8: devs.ExternalTransitionResponse
	(*ConfluentTransitionRequest)(nil),  // 9: devs.ConfluentTransitionRequest
	(*ConfluentTransitionResponse)(nil), // 10: devs.ConfluentTransitionResponse
	(*OutputRequest)(nil),               // 11: devs.OutputRequest
	(*OutputResponse)(nil),              // 12: devs.OutputResponse
	(*GetStateRequest)(nil),             // 13: devs.GetStateRequest
	(*GetStateResponse)(nil),            // 14: devs.GetStateResponse
}
var file_runners_proto_devs_proto_depIdxs = []int32{
	4,  // 0: devs.ExternalTransitionRequest.inputs:type_name -> devs.PortEvent
	4,  // 1: devs.ConfluentTransitionRequest.inputs:type_name -> devs.PortEvent
	4,  // 2: devs.OutputResponse.outputs:type_name -> devs.PortEvent
	0,  // 3: devs.DevsModel.Initialize:input_type -> devs.InitializeRequest
	2,  // 4: devs.DevsModel.TimeAdvance:input_type -> devs.TimeAdvanceRequest
	5,  // 5: devs.DevsModel.InternalTransition:input_type -> devs.InternalTransitionRequest
	7,  // 6: devs.DevsModel.ExternalTransition:input_type -> devs.ExternalTransitionRequest
	9,  // 7: devs.DevsModel.ConfluentTransition:input_type -> devs.ConfluentTransitionRequest
	11, // 8: devs.DevsModel.Output:input_type -> devs.OutputRequest
	13, // 9: devs.DevsModel.GetState:input_type -> devs.GetStateRequest
	1,  // 10: devs.DevsModel.Initialize:output_type -> devs.InitializeResponse
	3,  // 11: devs.DevsModel.TimeAdvance:output_type -> devs.TimeAdvanceResponse
	6,  // 12: devs.DevsModel.InternalTransition:output_type -> devs.InternalTransitionResponse
	8,  // 13: devs.DevsModel.ExternalTransition:output_type -> devs.ExternalTransitionResponse
	10, // 14: devs.DevsModel.ConfluentTransition:output_type -> devs.ConfluentTransitionResponse
	12, // 15: devs.DevsModel.Output:output_type -> devs.OutputResponse
	14, // 16: devs.DevsModel.GetState:output_type -> devs.GetStateResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_runners_proto_devs_proto_init() }
func file_runners_proto_devs_proto_init() {
	if File_runners_proto_devs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runners_proto_devs_proto_rawDesc), len(file_runners_proto_devs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runners_proto_devs_proto_goTypes,
		DependencyIndexes: file_runners_proto_devs_proto_depIdxs,
		MessageInfos:      file_runners_proto_devs_proto_msgTypes,
	}.Build()
	File_runners_proto_devs_proto = out.File
	file_runners_proto_devs_proto_goTypes = nil
	file_runners_proto_devs_proto_depIdxs = nil
}
