// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: devs.proto

package devspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Temps écoulé depuis la dernière transition
type ElapsedTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElapsedTime) Reset() {
	*x = ElapsedTime{}
	mi := &file_devs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElapsedTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElapsedTime) ProtoMessage() {}

func (x *ElapsedTime) ProtoReflect() protoreflect.Message {
	mi := &file_devs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElapsedTime.ProtoReflect.Descriptor instead.
func (*ElapsedTime) Descriptor() ([]byte, []int) {
	return file_devs_proto_rawDescGZIP(), []int{0}
}

func (x *ElapsedTime) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Réponse de TimeAdvance() : sigma
type TimeAdvanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sigma         float64                `protobuf:"fixed64,1,opt,name=sigma,proto3" json:"sigma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeAdvanceResponse) Reset() {
	*x = TimeAdvanceResponse{}
	mi := &file_devs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeAdvanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeAdvanceResponse) ProtoMessage() {}

func (x *TimeAdvanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeAdvanceResponse.ProtoReflect.Descriptor instead.
func (*TimeAdvanceResponse) Descriptor() ([]byte, []int) {
	return file_devs_proto_rawDescGZIP(), []int{1}
}

func (x *TimeAdvanceResponse) GetSigma() float64 {
	if x != nil {
		return x.Sigma
	}
	return 0
}

// Message pour injecter une valeur dans un port d'entrée
type InputMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nom du port d'entrée (GetInPort(portName))
	PortName string `protobuf:"bytes,1,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`
	// Valeur sérialisée en JSON (pour rester agnostique au type)
	ValueJson     string `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputMessage) Reset() {
	*x = InputMessage{}
	mi := &file_devs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputMessage) ProtoMessage() {}

func (x *InputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_devs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputMessage.ProtoReflect.Descriptor instead.
func (*InputMessage) Descriptor() ([]byte, []int) {
	return file_devs_proto_rawDescGZIP(), []int{2}
}

func (x *InputMessage) GetPortName() string {
	if x != nil {
		return x.PortName
	}
	return ""
}

func (x *InputMessage) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

// Valeurs produites sur un port de sortie lors de Output()
type PortOutput struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PortName string                 `protobuf:"bytes,1,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`
	// Toutes les valeurs présentes sur ce port (sérialisées en JSON)
	ValuesJson    []string `protobuf:"bytes,2,rep,name=values_json,json=valuesJson,proto3" json:"values_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortOutput) Reset() {
	*x = PortOutput{}
	mi := &file_devs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortOutput) ProtoMessage() {}

func (x *PortOutput) ProtoReflect() protoreflect.Message {
	mi := &file_devs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortOutput.ProtoReflect.Descriptor instead.
func (*PortOutput) Descriptor() ([]byte, []int) {
	return file_devs_proto_rawDescGZIP(), []int{3}
}

func (x *PortOutput) GetPortName() string {
	if x != nil {
		return x.PortName
	}
	return ""
}

func (x *PortOutput) GetValuesJson() []string {
	if x != nil {
		return x.ValuesJson
	}
	return nil
}

// Réponse de Output() : ensemble des sorties générées
type OutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*PortOutput          `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputResponse) Reset() {
	*x = OutputResponse{}
	mi := &file_devs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputResponse) ProtoMessage() {}

func (x *OutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputResponse.ProtoReflect.Descriptor instead.
func (*OutputResponse) Descriptor() ([]byte, []int) {
	return file_devs_proto_rawDescGZIP(), []int{4}
}

func (x *OutputResponse) GetOutputs() []*PortOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_devs_proto protoreflect.FileDescriptor

const file_devs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"devs.proto\x12\x0edevsforge.devs\x1a\x1bgoogle/protobuf/empty.proto\"#\n" +
	"\vElapsedTime\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"+\n" +
	"\x13TimeAdvanceResponse\x12\x14\n" +
	"\x05sigma\x18\x01 \x01(\x01R\x05sigma\"J\n" +
	"\fInputMessage\x12\x1b\n" +
	"\tport_name\x18\x01 \x01(\tR\bportName\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\"J\n" +
	"\n" +
	"PortOutput\x12\x1b\n" +
	"\tport_name\x18\x01 \x01(\tR\bportName\x12\x1f\n" +
	"\vvalues_json\x18\x02 \x03(\tR\n" +
	"valuesJson\"F\n" +
	"\x0eOutputResponse\x124\n" +
	"\aoutputs\x18\x01 \x03(\v2\x1a.devsforge.devs.PortOutputR\aoutputs2\xbb\x04\n" +
	"\x12AtomicModelService\x12<\n" +
	"\n" +
	"Initialize\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bFinalize\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\vTimeAdvance\x12\x16.google.protobuf.Empty\x1a#.devsforge.devs.TimeAdvanceResponse\x12D\n" +
	"\x12InternalTransition\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x12ExternalTransition\x12\x1b.devsforge.devs.ElapsedTime\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x13ConfluentTransition\x12\x1b.devsforge.devs.ElapsedTime\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x06Output\x12\x16.google.protobuf.Empty\x1a\x1e.devsforge.devs.OutputResponse\x12@\n" +
	"\bAddInput\x12\x1c.devsforge.devs.InputMessage\x1a\x16.google.protobuf.EmptyB)Z'devsforge/simulator/runner/proto;devspbb\x06proto3"

var (
	file_devs_proto_rawDescOnce sync.Once
	file_devs_proto_rawDescData []byte
)

func file_devs_proto_rawDescGZIP() []byte {
	file_devs_proto_rawDescOnce.Do(func() {
		file_devs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devs_proto_rawDesc), len(file_devs_proto_rawDesc)))
	})
	return file_devs_proto_rawDescData
}

var file_devs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_devs_proto_goTypes = []any{
	(*ElapsedTime)(nil),         // 0: devsforge.devs.ElapsedTime
	(*TimeAdvanceResponse)(nil), // 1: devsforge.devs.TimeAdvanceResponse
	(*InputMessage)(nil),        // 2: devsforge.devs.InputMessage
	(*PortOutput)(nil),          // 3: devsforge.devs.PortOutput
	(*OutputResponse)(nil),      // 4: devsforge.devs.OutputResponse
	(*emptypb.Empty)(nil),       // 5: google.protobuf.Empty
}
var file_devs_proto_depIdxs = []int32{
	3, // 0: devsforge.devs.OutputResponse.outputs:type_name -> devsforge.devs.PortOutput
	5, // 1: devsforge.devs.AtomicModelService.Initialize:input_type -> google.protobuf.Empty
	5, // 2: devsforge.devs.AtomicModelService.Finalize:input_type -> google.protobuf.Empty
	5, // 3: devsforge.devs.AtomicModelService.TimeAdvance:input_type -> google.protobuf.Empty
	5, // 4: devsforge.devs.AtomicModelService.InternalTransition:input_type -> google.protobuf.Empty
	0, // 5: devsforge.devs.AtomicModelService.ExternalTransition:input_type -> devsforge.devs.ElapsedTime
	0, // 6: devsforge.devs.AtomicModelService.ConfluentTransition:input_type -> devsforge.devs.ElapsedTime
	5, // 7: devsforge.devs.AtomicModelService.Output:input_type -> google.protobuf.Empty
	2, // 8: devsforge.devs.AtomicModelService.AddInput:input_type -> devsforge.devs.InputMessage
	5, // 9: devsforge.devs.AtomicModelService.Initialize:output_type -> google.protobuf.Empty
	5, // 10: devsforge.devs.AtomicModelService.Finalize:output_type -> google.protobuf.Empty
	1, // 11: devsforge.devs.AtomicModelService.TimeAdvance:output_type -> devsforge.devs.TimeAdvanceResponse
	5, // 12: devsforge.devs.AtomicModelService.InternalTransition:output_type -> google.protobuf.Empty
	5, // 13: devsforge.devs.AtomicModelService.ExternalTransition:output_type -> google.protobuf.Empty
	5, // 14: devsforge.devs.AtomicModelService.ConfluentTransition:output_type -> google.protobuf.Empty
	4, // 15: devsforge.devs.AtomicModelService.Output:output_type -> devsforge.devs.OutputResponse
	5, // 16: devsforge.devs.AtomicModelService.AddInput:output_type -> google.protobuf.Empty
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_devs_proto_init() }
func file_devs_proto_init() {
	if File_devs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devs_proto_rawDesc), len(file_devs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devs_proto_goTypes,
		DependencyIndexes: file_devs_proto_depIdxs,
		MessageInfos:      file_devs_proto_msgTypes,
	}.Build()
	File_devs_proto = out.File
	file_devs_proto_goTypes = nil
	file_devs_proto_depIdxs = nil
}
