# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: devs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'devs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndevs.proto\x12\x0e\x64\x65vsforge.devs\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0b\x45lapsedTime\x12\r\n\x05value\x18\x01 \x01(\x01\"$\n\x13TimeAdvanceResponse\x12\r\n\x05sigma\x18\x01 \x01(\x01\"5\n\x0cInputMessage\x12\x11\n\tport_name\x18\x01 \x01(\t\x12\x12\n\nvalue_json\x18\x02 \x01(\t\"4\n\nPortOutput\x12\x11\n\tport_name\x18\x01 \x01(\t\x12\x13\n\x0bvalues_json\x18\x02 \x03(\t\"=\n\x0eOutputResponse\x12+\n\x07outputs\x18\x01 \x03(\x0b\x32\x1a.devsforge.devs.PortOutput2\xbb\x04\n\x12\x41tomicModelService\x12<\n\nInitialize\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n\x08\x46inalize\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12J\n\x0bTimeAdvance\x12\x16.google.protobuf.Empty\x1a#.devsforge.devs.TimeAdvanceResponse\x12\x44\n\x12InternalTransition\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12I\n\x12\x45xternalTransition\x12\x1b.devsforge.devs.ElapsedTime\x1a\x16.google.protobuf.Empty\x12J\n\x13\x43onfluentTransition\x12\x1b.devsforge.devs.ElapsedTime\x1a\x16.google.protobuf.Empty\x12@\n\x06Output\x12\x16.google.protobuf.Empty\x1a\x1e.devsforge.devs.OutputResponse\x12@\n\x08\x41\x64\x64Input\x12\x1c.devsforge.devs.InputMessage\x1a\x16.google.protobuf.EmptyB)Z\'devsforge/simulator/runner/proto;devspbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'devs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'devsforge/simulator/runner/proto;devspb'
  _globals['_ELAPSEDTIME']._serialized_start=59
  _globals['_ELAPSEDTIME']._serialized_end=87
  _globals['_TIMEADVANCERESPONSE']._serialized_start=89
  _globals['_TIMEADVANCERESPONSE']._serialized_end=125
  _globals['_INPUTMESSAGE']._serialized_start=127
  _globals['_INPUTMESSAGE']._serialized_end=180
  _globals['_PORTOUTPUT']._serialized_start=182
  _globals['_PORTOUTPUT']._serialized_end=234
  _globals['_OUTPUTRESPONSE']._serialized_start=236
  _globals['_OUTPUTRESPONSE']._serialized_end=297
  _globals['_ATOMICMODELSERVICE']._serialized_start=300
  _globals['_ATOMICMODELSERVICE']._serialized_end=871
# @@protoc_insertion_point(module_scope)
